# Generated by Django 5.0.7 on 2024-07-27 23:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StepWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("step_data", models.JSONField(blank=True, null=True)),
                ("conditions", models.JSONField(blank=True, null=True)),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("enhancement", "enhancement"),
                            ("logic", "logic"),
                            ("decision", "decision"),
                            ("waiting", "waiting"),
                        ],
                        max_length=11,
                    ),
                ),
                (
                    "timing",
                    models.CharField(
                        choices=[("sync", "sync"), ("async", "async")], max_length=5
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
